ASSERTION_SUCCESSFUL = 1
ASSERTION_PERFORMANCE_PROBLEMS = 2
ASSERTION_FAILED = 3
ASSERTION_COMPLETE_OUTAGE = 4

COMPONENT_OPERATIONAL = 1
COMPONENT_PERFORMANCE_PROBLEMS = 2
COMPONENT_PARTIAL_OUTAGE = 3
COMPONENT_COMPLETE_OUTAGE = 4
