ASSERTION_SUCCESSFUL = 0
ASSERTION_FAILED = 1
ASSERTION_PERFORMANCE_PROBLEMS = 2

COMPONENT_OPERATIONAL = 0
COMPONENT_PERFORMANCE_PROBLEMS = 1
COMPONENT_PARTIAL_OUTAGE = 2
COMPONENT_COMPLETE_OUTAGE = 3
